version: '3.1'
services:
  db:
    image: postgres
    container_name: users-db
    restart: always
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql